spring:
  messages:
    basename: i18n/messages

questionnaire:
  csv-paths:
    - csv/questions_ru.csv
    - csv/questions.csv
  csv-files:
    - locale: default
      path: csv/questions.csv
    - locale: ru_RU
      path: csv/questions_ru.csv